### ISSUE TITLE
Several bugs I encountered while doing the Reaktoro V2 tutorials

### ISSUE THREAD

**Issue by Kanonkessen** [reaktoro/reaktoro#227]
Greeting team Reaktoro !

To prepare for a (currently ongoing) internship in january 2022, I took interest in learning the basics of the Python programming language last month. During this internship, I am supposed to try and use Reaktoro for a project my company is working on (geothermal exploration). Since I am a complete new comer in the Pyhton / anaconda / github world, this is my first ever bug report so I apologize in advance if this report is not usually how it's done. I will try my best to explain the problems I encountered while going through the Reaktoro V2 tutorials, but first I must provide context about the systems I have been running Python / Reaktoro onto.  

My personnal computer runs on Windows7 (for several reasons) and is therefore on Python 3.7.11 (64 bits), my current IDE is spyder 5.2.1 and reaktoro V2 is the current most recent version : 2.0.0.rc8.  
My working computer runs on the latest Linux Mint version, with Python 3.9,9, spyder 5.2.1 and is also using Reaktoro V2.0.0rc8

Onto the bug report :  
_Nota Bene :_ unless stated otherwise, the code provided in the bug report is copy-pasted from the related tutorial page. If I have to provide my own code, I will explicitly state so in the text.  
Also, I will try and make an individual message dedicated to each bug in this current discussion. If you prefer that I open a different thread for each bug, I will simply copy-paste the content of the message in a new thread. 

[Defining chemical systems](https://reaktoro.org/tutorials/basics/defining-chemical-systems.html)
In the **Chemical system definition with many phases** section:  

The following code to print the automatically selected aqueous species  
```
db = PhreeqcDatabase("phreeqc.dat")

solution = AqueousPhase()
albite = MineralPhase("Albite")
kaolinite = MineralPhase("Kaolinite")

system = ChemicalSystem(db, albite, kaolinite, solution)

aqueousphase = system.phases().get("AqueousPhase")
for species in aqueousphase.species():
    print(species.name())

```
returns this error ;

```
Traceback (most recent call last):

  File "C:\Users\Kanon\AppData\Local\Temp/ipykernel_6720/4126200599.py", line 1, in <module>
    aqueousphase = system.phases().get("AqueousPhase")

AttributeError: 'reaktoro.reaktoro4py.PhaseList' object has no attribute 'get'
```

This error is reproducible on both my personnal computer and working computer.
Removing `get("AqueousPhase")` prints the list with aqueous species and minerals so the list is working as intended.

(cont...)

**Comment by Kanonkessen** [comment]
[Creating chemical states](https://reaktoro.org/tutorials/basics/creating-chemical-states.html)

This bug is related to the previous one because it also involves generating a list of aqueous species from a list of mineral phases.
The following code :
```
db = PhreeqcDatabase("pitzer.dat")

solution = AqueousPhase()
minerals = MineralPhase("Halite Calcite Dolomite Quartz")

system = ChemicalSystem(db, solution, minerals)

state = ChemicalState(system)
state.temperature(50.0, "celsius")
state.pressure(5.0, "atm")
state.set("H2O"     , 1.00, "kg")
state.set("Na+"     , 0.10, "mol")
state.set("Cl-"     , 0.10, "mol")
state.set("Ca+2"    , 0.50, "mmol")
state.set("Mg+2"    , 0.50, "mmol")
state.set("Calcite" , 1.00, "mg")
state.set("Dolomite", 1.00, "ug")
state.set("Quartz"  , 1.00, "kmol")

print(state)
```
returns the error 
```

Traceback (most recent call last):

  File "C:\Users\Kanon\AppData\Local\Temp/ipykernel_5712/1679728549.py", line 6, in <module>
    system = ChemicalSystem(db, solution, minerals)

RuntimeError: ***ERROR*** Could not find any Species object with formula H2O.
```
Reproducible on both environments setups.
That's an interesting error that I tinkered with a little bit. 

- Changing the database to the one used on the previous example `"phreeqc.dat"` returns the same error.
- Adding Kaolinite and Albite as mineral phases is impossible while using the current `"pitzer.dat"` database as there are not listed.
- Changing the database to `"phreeqc.dat"` AND adding Kaolinite and Albite to the mineral phases returns the correct list of phases and adds phases related to Kaolinite and Albite.
- addind the elements one by one with a `speciate("H O")` returns the same error with the following element 
```
Traceback (most recent call last):

  File "C:\Users\Kanon\AppData\Local\Temp/ipykernel_6240/2199014111.py", line 13, in <module>
    state.set("Na+"     , 0.10, "mol")

RuntimeError: ***ERROR*** Could not find any Species object with name Na+.
```
- `speciate()` with the correct list of chemical element in the aqueous phase returns the correct list of aqueous species

What we can deduce from this : the previous example of creating a list of aqueous species is working as intended in specific cases only. The Kaolinite / albite example from before is suitable for Reaktoro to populate aqueous species on its own, but  the `"Halite Calcite Dolomite Quartz"` is not.

**Comment by Kanonkessen** [comment]
The following bug has been found all across Reaktoro V2 tutorials and is therefore not linked to a tutorial chapter in particular.

When using the previous example of chemical state and `speciate()` to populate the aqueous species, the following code (tutorial code except for the `speciate()` part and the `"phreeqc.dat"` database choice
```

from reaktoro import *
db = PhreeqcDatabase("pitzer.dat")

solution = AqueousPhase(speciate("H O Na Cl C Ca Mg"))
minerals = MineralPhase("Halite Calcite Dolomite Quartz")

system = ChemicalSystem(db, solution, minerals)

state = ChemicalState(system)
state.temperature(50.0, "celsius")
state.pressure(5.0, "atm")
state.set("H2O"     , 1.00, "kg")
state.set("Na+"     , 0.10, "mol")
state.set("Cl-"     , 0.10, "mol")
state.set("Ca+2"    , 0.50, "mmol")
state.set("Mg+2"    , 0.50, "mmol")
state.set("Calcite" , 1.00, "mg")
state.set("Dolomite", 1.00, "ug")
state.set("Quartz"  , 1.00, "kmol")

print(state)
```
returns the following `ChemicalState` table : 

```
+-----------------+-------------+------+
| Property        |       Value | Unit |
+-----------------+-------------+------+
| Temperature     |      323.15 |    K |
| Pressure        |      506625 |   Pa |
| Element Amount: |             |      |
| :: H            |     111.012 |  mol |
| :: C            | 1.00017e-05 |  mol |
| :: O            |     2055.51 |  mol |
| :: Na           |         0.1 |  mol |
| :: Mg           | 0.000500005 |  mol |
| :: Si           |        1000 |  mol |
| :: Cl           |         0.1 |  mol |
| :: Ca           | 0.000509996 |  mol |
| Species Amount: |             |      |
| :: H+           |           0 |  mol |
| :: H2O          |     55.5062 |  mol |
| :: CO3-2        |           0 |  mol |
| :: CO2          |           0 |  mol |
| :: Ca+2         |      0.0005 |  mol |
| :: Cl-          |         0.1 |  mol |
| :: HCO3-        |           0 |  mol |
| :: Mg+2         |      0.0005 |  mol |
| :: MgCO3        |           0 |  mol |
| :: MgOH+        |           0 |  mol |
| :: Na+          |         0.1 |  mol |
| :: OH-          |           0 |  mol |
| :: Halite       |           0 |  mol |
| :: Calcite      |  9.9909e-06 |  mol |
| :: Dolomite     | 5.42278e-09 |  mol |
| :: Quartz       |        1000 |  mol |
+-----------------+-------------+------+ 
```
By the way, great job on making it looks good ! :+1: 

The "bug" in this table is related to the 0 values. reaktoro should be automatically change 0 values in `ChemicalState` and other objects to very little values instead. The default value is set to be 1e-16.
The tables provided in all tutorial pages indeed show the 0 values to be 1e-16 instead but all my prints were not incrementing the 1e-16 values automatically and instead incremented 0.

This bug is reproducible on both systems.

**Comment by allanleal** [comment]
Hi @Kanonkessen. Thanks for reporting this issue. I think this should be resolved by updating reaktoro to `v2.0rc9`. 

Activate the conda environment where you installed `reaktoro` (maybe `conda activate rkt` if the environment is called `rkt`), then `conda install reaktoro=v2.0rc9`). Let me know. You can also chat with me on Gitter (https://gitter.im/reaktoro/community)

**Comment by Kanonkessen** [comment]
Hey @allanleal 

I have several other bugs to report including a pretty annoying one related to the utf-8 codec. I will update my reaktoro to rc9 and test everything again. If I happen to find a bug which has not been fixed yet, I will start another thread and provide informations within. Is that ok with you ? 

Thanks for all your work by the way, it was really interesting going through the tutorials. I had no major issues following the steps provided. I will probably make a dedicated thread later from my complete new comer point of view.

**Comment by allanleal** [comment]
Thanks, @Kanonkessen , once more for your feedback. I'm glad to know the tutorials were clear to you. Please let me know if you find bugs (codes, tutorials) and if you have suggestions for improvements.

**Comment by Kanonkessen** [comment]
`conda install reaktoro=v2.0rc9` returned a `PackageNotFound` error so I went directly to the anaconda repo [here](https://anaconda.org/conda-forge/reaktoro) and reinstalled reaktoro from scratch using : 

`conda install -c conda-forge reaktoro`

I already confirm that the bugs in this current discussion have been fixed when updating to version 2.0.0rc9 but the utf-8 error is still around so I will continue testing the other bugs I encountered and make a new thread about them. Therefrore, you can mark this thread as closed.

**Comment by allanleal** [comment]
Right, I misspelled the version name. The command should be `conda install reaktoro=2.0.0rc9`, without `v`.

OK, looking forward to getting more details about the utf-8 errors (this may be caused by symbols such as m³, · (center dot), etc.
